version: '3.8'
services:
  app-principal:
    image: catastrofes_ambientais
    container_name: app_principal
    build:
      context: ../catastrofes-ambientais
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catastrofes
    ports:
      - "3306:3306"
