name: CI/CD para Testes Automatizados em Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código fonte
    - name: Checkout do Código
      uses: actions/checkout@v3

    # Configuração do JDK
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    # Instalar dependências do projeto
    - name: Build do Projeto com Maven
      run: mvn install -DskipTests

    # Iniciar Docker Compose para rodar o projeto principal
    - name: Iniciar Docker Compose
      run: docker-compose up -d

    # Aguardar um tempo para garantir que o projeto esteja totalmente inicializado
    - name: Aguardar 30 segundos
      run: sleep 30

    # Executar os testes automatizados
    - name: Executar Testes
      run: mvn test

    # Publicar os relatórios de testes 
    - name: Publicar Relatórios de Teste
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: relatorios-de-testes
        path: target/surefire-reports/

    # Parar Docker Compose após os testes
    - name: Parar Docker Compose
      run: docker-compose down
